#!/usr/bin/env groovy

library identifier: 'jenkins-shared-library@main', retriever: modernSCM(
        [$class: 'GitSCMSource',
         remote: 'https://shograd:glpat-17RPPxeFNYVtsdwxk4oA@gitlab.com/shograd/jenkins-shared-library.git'
         ]
)

def gv

pipeline {
    agent any
    tools {
        maven 'maven-3.8'
    }
    stages {
        stage("init") {
            steps {
                script {
                    echo "load scripts..."
                    gv = load "script.groovy"
                }
            }
        }
        stage("build jar") {
            steps {
                script {
                    echo "building jar"
                    buildJar()
                }
            }
        }
        stage("build and push") {
            steps {
                script {
                    buildImage 'shograd/demo-app:jma-3.0'
                    dockerLogin()
                    dockerPush 'shograd/demo-app:jma-3.0'
                }
            }
        }
        stage("deploy") {
            steps {
                script {
                    //echo "deploying"
                    gv.deployApp()
                }
            }
        }
    }   
}
